apiVersion: v1
kind: ConfigMap
metadata:
  name: account-service-config
data:
  application.yaml: |
    simplematch:
      account-service:
        grpc:
          enabled: true
        lifecycle-consumer:
          enabled: true
        final-matching-events:
          enabled: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: persistence-config
data:
  application.yaml: |
    simplematch:
      persistence:
        matching-events:
          enabled: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: market-data-projection-config
data:
  application.yaml: |
    simplematch:
      market-data-projection:
        matching-events:
          enabled: true
        marketdata-events:
          enabled: true
        redis:
          enabled: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: marketdata-publisher-config
data:
  application.yaml: |
    simplematch:
      marketdata-publisher:
        enabled: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: query-service-config
data:
  application.yaml: |
    simplematch:
      query-service:
        matching-events:
          enabled: true
        account-lifecycle:
          enabled: true
        redis:
          enabled: true
        market-reference:
          install-on-startup: true
