apiVersion: v1
kind: Service
metadata:
  name: matching-headless
  labels:
    app.kubernetes.io/name: matching
    app.kubernetes.io/part-of: simplematch
spec:
  clusterIP: None
  ports:
    - name: runtime-status
      port: 8081
      targetPort: runtime-status
      protocol: TCP
  selector:
    app.kubernetes.io/name: matching
