apiVersion: v1
kind: ServiceAccount
metadata:
  name: matching
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: matching-partition-lease-holder
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    resourceNames:
      - matching-partition-00
      - matching-partition-01
      - matching-partition-02
      - matching-partition-03
      - matching-partition-04
      - matching-partition-05
      - matching-partition-06
      - matching-partition-07
      - matching-partition-08
      - matching-partition-09
      - matching-partition-10
      - matching-partition-11
      - matching-partition-12
      - matching-partition-13
      - matching-partition-14
    verbs: ["get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: matching-partition-lease-holder
subjects:
  - kind: ServiceAccount
    name: matching
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: matching-partition-lease-holder
