apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: matching
  labels:
    app.kubernetes.io/name: matching
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: matching
