apiVersion: v1
kind: ServiceAccount
metadata:
  name: quickfix-gateway
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: quickfix-gateway-configuration-reader
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["simplematch-platform-config", "quickfix-gateway-config"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["quickfix-gateway-secrets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: quickfix-gateway-configuration-reader
subjects:
  - kind: ServiceAccount
    name: quickfix-gateway
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: quickfix-gateway-configuration-reader
