apiVersion: v1
kind: ConfigMap
metadata:
  name: risk-service-outbox-connector
data:
  connector.json: |
    {
      "name": "risk-service-outbox",
      "config": {
        "config.providers": "env",
        "config.providers.env.class": "org.apache.kafka.common.config.provider.EnvVarConfigProvider",
        "connector.class": "io.debezium.connector.postgresql.PostgresConnector",
        "tasks.max": "1",
        "database.hostname": "${env:SIMPLEMATCH_POSTGRES_HOSTNAME}",
        "database.port": "${env:SIMPLEMATCH_POSTGRES_PORT}",
        "database.user": "${env:RISK_SERVICE_POSTGRES_USER}",
        "database.password": "${env:RISK_SERVICE_POSTGRES_PASSWORD}",
        "database.dbname": "${env:SIMPLEMATCH_POSTGRES_DBNAME}",
        "database.sslmode": "${env:SIMPLEMATCH_POSTGRES_SSLMODE}",
        "database.sslrootcert": "${env:SIMPLEMATCH_POSTGRES_SSLROOTCERT}",
        "topic.prefix": "simplematch-risk-service",
        "plugin.name": "pgoutput",
        "slot.name": "risk_service_outbox",
        "publication.name": "dbz_risk_service_outbox",
        "publication.autocreate.mode": "filtered",
        "table.include.list": "risk_service.outbox",
        "tombstones.on.delete": "false",
        "key.converter": "org.apache.kafka.connect.storage.StringConverter",
        "key.converter.schemas.enable": "false",
        "value.converter": "org.apache.kafka.connect.converters.ByteArrayConverter",
        "transforms": "outbox",
        "transforms.outbox.type": "io.debezium.transforms.outbox.EventRouter",
        "transforms.outbox.route.by.field": "topic",
        "transforms.outbox.route.topic.replacement": "${routedByValue}",
        "transforms.outbox.table.field.event.id": "event_id",
        "transforms.outbox.table.field.event.key": "message_key",
        "transforms.outbox.table.field.event.payload": "payload",
        "transforms.outbox.table.field.event.timestamp": "created_at",
        "transforms.outbox.table.field.event.type": "payload_type",
        "transforms.outbox.table.fields.additional.placement": "kafka_partition_id:partition,headers_json:header:headers_json"
      }
    }
