apiVersion: v1
kind: ConfigMap
metadata:
  name: risk-service-config
data:
  application.yaml: |
    simplematch:
      risk-service:
        admission:
          cdc-metric-name: orders.validated
          maximum-cdc-lag-events: 10000
          maximum-metric-age: 30s