apiVersion: v1
kind: ConfigMap
metadata:
  name: simplematch-platform-config
data:
  application.yaml: |
    logging:
      structured:
        format:
          console: ecs
        ecs:
          service:
            environment: ${simplematch.environment}
    simplematch:
      environment: local
      kafka:
        brokers: kafka:9092
        topics:
          matching-commands: matching.commands
          matching-events: matching.events
          marketdata-events: marketdata.events
        partitions:
          matching-commands: 15
          matching-events: 15
      grpc:
        targets:
          account-service: dns:///account-service:50051
          risk-service: dns:///risk-service:50052
      market:
        currency: TWD
        time-zone: Asia/Taipei
      redis:
        endpoints: redis:6379
