apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: simplematch-rwo-pod
  labels:
    app.kubernetes.io/part-of: simplematch
    simplematch.io/managed-by: cluster-manager
provisioner: rancher.io/local-path
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: false
