package com.simplematch.riskservice.store;

import static org.assertj.core.api.Assertions.assertThat;

import java.util.List;
import java.util.UUID;
import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

class RiskServiceFlywayMigrationTest {
  private static final String SCHEMA_NAME = "RISK_SERVICE";

  // Verify that the Flyway migration removes legacy outbox relay columns and indexes while preserving current columns.
  // Scenario: create the legacy schema first, then run the risk-service migration and validate the upgrade result.
  @DisplayName("Flyway migration removes legacy relay columns and indexes")
  @Test
  void migrateDropsLegacyRelayColumnsFromExistingOutboxSchema() {
    final DriverManagerDataSource dataSource = new DriverManagerDataSource();
    dataSource.setDriverClassName("org.h2.Driver");
    dataSource.setUrl("jdbc:h2:mem:" + UUID.randomUUID() + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1");
    final JdbcTemplate jdbcTemplate = new JdbcTemplate(dataSource);

    jdbcTemplate.execute(
        """
      CREATE SCHEMA IF NOT EXISTS risk_service
      """);
    jdbcTemplate.execute(
      """
      CREATE TABLE risk_service.outbox (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          event_id VARCHAR(255) NOT NULL UNIQUE,
          topic VARCHAR(255) NOT NULL,
          message_key VARCHAR(255) NOT NULL,
          payload BYTEA NOT NULL,
          payload_type VARCHAR(255) NOT NULL,
          headers_json TEXT NOT NULL,
          aggregate_type VARCHAR(255) NOT NULL,
          aggregate_id VARCHAR(255) NOT NULL,
          created_at_unix_ms BIGINT NOT NULL,
          available_at_unix_ms BIGINT,
          published_at_unix_ms BIGINT,
          lease_token VARCHAR(255),
          lease_expires_at_unix_ms BIGINT,
          publish_attempts INTEGER,
          last_error TEXT
        )
        """);
    jdbcTemplate.execute(
        """
        CREATE TABLE risk_service.risk_submissions (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          idempotency_key VARCHAR(255) NOT NULL UNIQUE,
          request_id VARCHAR(255) NOT NULL,
          order_id VARCHAR(255) NOT NULL,
          client_order_id VARCHAR(255) NOT NULL,
          original_client_order_id VARCHAR(255) NOT NULL,
          command_type VARCHAR(64) NOT NULL,
          accepted BOOLEAN NOT NULL,
          reason_code VARCHAR(255) NOT NULL,
          reason_text TEXT NOT NULL,
          created_at_unix_ms BIGINT NOT NULL,
          outbox_event_id VARCHAR(255) NOT NULL UNIQUE
        )
        """);
    jdbcTemplate.execute(
        "CREATE INDEX idx_outbox_publishable ON risk_service.outbox (available_at_unix_ms, id)");

    Flyway.configure()
        .baselineOnMigrate(true)
        .baselineVersion("1")
        .dataSource(dataSource)
        .locations("classpath:db/migration/risk-service")
        .load()
        .migrate();

    for (String columnName :
        List.of(
            "AVAILABLE_AT_UNIX_MS",
            "PUBLISHED_AT_UNIX_MS",
            "LEASE_TOKEN",
            "LEASE_EXPIRES_AT_UNIX_MS",
            "PUBLISH_ATTEMPTS",
            "LAST_ERROR")) {
      assertThat(hasColumn(jdbcTemplate, columnName)).isFalse();
    }
    assertThat(hasColumn(jdbcTemplate, "TOPIC")).isTrue();
    assertThat(hasColumn(jdbcTemplate, "KAFKA_PARTITION_ID")).isTrue();
    assertThat(hasColumn(jdbcTemplate, "CREATED_AT_UNIX_MS")).isTrue();
    assertThat(hasIndex(jdbcTemplate, "IDX_OUTBOX_PUBLISHABLE")).isFalse();
  }

  private boolean hasColumn(JdbcTemplate jdbcTemplate, String columnName) {
    return jdbcTemplate.queryForObject(
            """
            SELECT COUNT(*)
            FROM INFORMATION_SCHEMA.COLUMNS
            WHERE UPPER(TABLE_SCHEMA) = ?
              AND UPPER(TABLE_NAME) = 'OUTBOX'
              AND UPPER(COLUMN_NAME) = ?
            """,
            Integer.class,
            SCHEMA_NAME,
            columnName)
        > 0;
  }

  private boolean hasIndex(JdbcTemplate jdbcTemplate, String indexName) {
    return jdbcTemplate.queryForObject(
            """
            SELECT COUNT(*)
            FROM INFORMATION_SCHEMA.INDEXES
            WHERE UPPER(TABLE_SCHEMA) = ?
              AND UPPER(TABLE_NAME) = 'OUTBOX'
              AND UPPER(INDEX_NAME) = ?
            """,
            Integer.class,
            SCHEMA_NAME,
            indexName)
        > 0;
  }
}