[versions]
spring-boot = "3.5.14"
spring-cloud = "2025.0.1"
spring-dependency-management = "1.1.7"
protobuf-gradle-plugin = "0.9.5"
protobuf = "4.31.1"
grpc = "1.80.0"
flyway = "12.7.0"
spotbugs-gradle-plugin = "6.2.4"
spotbugs-tool = "4.9.4"
errorprone-gradle-plugin = "4.3.0"
errorprone = "2.39.0"
checkstyle = "10.26.1"
lombok = "1.18.42"
mockito = "5.17.0"
jackson = "2.19.2"
uuid-creator = "6.1.1"
junit = "5.12.2"
junit-platform = "1.12.2"
jakarta-annotation = "3.0.0"
quickfixj = "3.0.1"

[libraries]
errorprone-annotations = { module = "com.google.errorprone:error_prone_annotations", version.ref = "errorprone" }
errorprone-core = { module = "com.google.errorprone:error_prone_core", version.ref = "errorprone" }
flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
flyway-database-postgresql = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway" }
flyway-gradle-plugin = { module = "org.flywaydb:flyway-gradle-plugin", version.ref = "flyway" }
grpc-netty-shaded = { module = "io.grpc:grpc-netty-shaded", version.ref = "grpc" }
grpc-protobuf = { module = "io.grpc:grpc-protobuf", version.ref = "grpc" }
grpc-protoc-gen-java = { module = "io.grpc:protoc-gen-grpc-java", version.ref = "grpc" }
grpc-stub = { module = "io.grpc:grpc-stub", version.ref = "grpc" }
jakarta-annotation-api = { module = "jakarta.annotation:jakarta.annotation-api", version.ref = "jakarta-annotation" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
protobuf-java = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf" }
protobuf-protoc = { module = "com.google.protobuf:protoc", version.ref = "protobuf" }
quickfixj-core = { module = "org.quickfixj:quickfixj-core", version.ref = "quickfixj" }
quickfixj-messages-fix44 = { module = "org.quickfixj:quickfixj-messages-fix44", version.ref = "quickfixj" }
uuid-creator = { module = "com.github.f4b6a3:uuid-creator", version.ref = "uuid-creator" }

[plugins]
errorprone = { id = "net.ltgt.errorprone", version.ref = "errorprone-gradle-plugin" }
protobuf = { id = "com.google.protobuf", version.ref = "protobuf-gradle-plugin" }
spotbugs = { id = "com.github.spotbugs", version.ref = "spotbugs-gradle-plugin" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
