CREATE SCHEMA IF NOT EXISTS risk_service;

CREATE TABLE risk_service.risk_submissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id VARCHAR(255) NOT NULL,
  sender_comp_id VARCHAR(255) NOT NULL,
  target_comp_id VARCHAR(255) NOT NULL,
  trading_day DATE NOT NULL,
  order_id VARCHAR(255) NOT NULL,
  cl_ord_id VARCHAR(255) NOT NULL,
  orig_cl_ord_id VARCHAR(255) NOT NULL,
  raw_cl_ord_id TEXT NOT NULL,
  raw_orig_cl_ord_id TEXT NOT NULL,
  command_type VARCHAR(64) NOT NULL,
  accepted BOOLEAN NOT NULL,
  reason_code VARCHAR(255) NOT NULL,
  reason_text TEXT NOT NULL,
  business_key_surrogated BOOLEAN NOT NULL DEFAULT FALSE,
  created_at_unix_ms BIGINT NOT NULL,
  outbox_event_id UUID NOT NULL UNIQUE,
  CONSTRAINT risk_submissions_business_key_key UNIQUE (
    sender_comp_id,
    target_comp_id,
    trading_day,
    command_type,
    cl_ord_id,
    business_key_surrogated
  ),
  CONSTRAINT ck_risk_submissions_command_type CHECK (
    command_type IN ('COMMAND_TYPE_UNSPECIFIED', 'COMMAND_TYPE_NEW', 'COMMAND_TYPE_CANCEL')),
  CONSTRAINT ck_risk_submissions_created_at CHECK (created_at_unix_ms >= 0)
);

CREATE TABLE risk_service.outbox (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id UUID NOT NULL UNIQUE,
  topic VARCHAR(255) NOT NULL,
  message_key VARCHAR(255) NOT NULL,
  kafka_partition_id INTEGER,
  payload BYTEA NOT NULL,
  payload_type VARCHAR(255) NOT NULL,
  headers_json TEXT NOT NULL,
  aggregate_type VARCHAR(255) NOT NULL,
  aggregate_id VARCHAR(255) NOT NULL,
  created_at_unix_ms BIGINT NOT NULL,
  CONSTRAINT ck_outbox_required_text CHECK (
    LENGTH(TRIM(topic)) > 0
    AND LENGTH(TRIM(payload_type)) > 0
    AND LENGTH(TRIM(headers_json)) > 0
    AND LENGTH(TRIM(aggregate_type)) > 0),
  CONSTRAINT ck_outbox_partition CHECK (kafka_partition_id IS NULL OR kafka_partition_id >= 0),
  CONSTRAINT ck_outbox_payload CHECK (OCTET_LENGTH(payload) > 0),
  CONSTRAINT ck_outbox_created_at CHECK (created_at_unix_ms >= 0)
);

CREATE INDEX idx_outbox_created_at
  ON risk_service.outbox (created_at_unix_ms, id);
