CREATE SCHEMA IF NOT EXISTS risk_service;

CREATE TABLE IF NOT EXISTS risk_service.risk_submissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  idempotency_key VARCHAR(255) NOT NULL UNIQUE,
  request_id VARCHAR(255) NOT NULL,
  order_id VARCHAR(255) NOT NULL,
  client_order_id VARCHAR(255) NOT NULL,
  original_client_order_id VARCHAR(255) NOT NULL,
  command_type VARCHAR(64) NOT NULL,
  accepted BOOLEAN NOT NULL,
  reason_code VARCHAR(255) NOT NULL,
  reason_text TEXT NOT NULL,
  created_at_unix_ms BIGINT NOT NULL,
  outbox_event_id VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS risk_service.outbox (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id VARCHAR(255) NOT NULL UNIQUE,
  topic VARCHAR(255) NOT NULL,
  message_key VARCHAR(255) NOT NULL,
  payload BYTEA NOT NULL,
  payload_type VARCHAR(255) NOT NULL,
  headers_json TEXT NOT NULL,
  aggregate_type VARCHAR(255) NOT NULL,
  aggregate_id VARCHAR(255) NOT NULL,
  created_at_unix_ms BIGINT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_outbox_created_at
  ON risk_service.outbox (created_at_unix_ms, id);