CREATE SCHEMA IF NOT EXISTS risk_service;

CREATE TABLE risk_service.outbox
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id           UUID         NOT NULL UNIQUE,
    topic              VARCHAR(255) NOT NULL,
    message_key        VARCHAR(255) NOT NULL,
    kafka_partition_id INTEGER,
    payload            BYTEA        NOT NULL,
    payload_type       VARCHAR(255) NOT NULL,
    headers_json       TEXT         NOT NULL,
    aggregate_type     VARCHAR(255) NOT NULL,
    aggregate_id       VARCHAR(255) NOT NULL,
    created_at_unix_ms BIGINT       NOT NULL,
    CONSTRAINT ck_outbox_required_text CHECK (
        LENGTH(TRIM(topic)) > 0
            AND LENGTH(TRIM(payload_type)) > 0
            AND LENGTH(TRIM(headers_json)) > 0
            AND LENGTH(TRIM(aggregate_type)) > 0),
    CONSTRAINT ck_outbox_partition CHECK (kafka_partition_id IS NULL OR kafka_partition_id >= 0),
    CONSTRAINT ck_outbox_payload CHECK (OCTET_LENGTH(payload) > 0),
    CONSTRAINT ck_outbox_created_at CHECK (created_at_unix_ms >= 0)
);

CREATE INDEX idx_outbox_created_at
    ON risk_service.outbox (created_at_unix_ms, id);
