CREATE TABLE risk_service.admission_journal (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  command_id UUID NOT NULL UNIQUE,
  order_id UUID NOT NULL,
  account_id UUID NOT NULL,
  symbol VARCHAR(64) NOT NULL,
  venue_mic VARCHAR(4) NOT NULL,
  side VARCHAR(32) NOT NULL,
  quantity BIGINT NOT NULL,
  limit_price_units BIGINT,
  order_type VARCHAR(32) NOT NULL,
  tif VARCHAR(32) NOT NULL,
  trading_day DATE NOT NULL,
  sender_comp_id VARCHAR(255) NOT NULL,
  target_comp_id VARCHAR(255) NOT NULL,
  cl_ord_id VARCHAR(255) NOT NULL,
  routing_snapshot_id UUID,
  routing_partition INTEGER,
  state VARCHAR(32) NOT NULL,
  reservation_id UUID,
  reason_code VARCHAR(255) NOT NULL DEFAULT '',
  reason_detail TEXT NOT NULL DEFAULT '',
  version BIGINT NOT NULL DEFAULT 0,
  created_at_unix_ms BIGINT NOT NULL,
  updated_at_unix_ms BIGINT NOT NULL,
  CONSTRAINT uq_admission_business_key UNIQUE (sender_comp_id, target_comp_id, trading_day, cl_ord_id),
  CONSTRAINT ck_admission_side CHECK (side IN ('SIDE_BUY', 'SIDE_SELL')),
  CONSTRAINT ck_admission_quantity CHECK (quantity > 0),
  CONSTRAINT ck_admission_state CHECK (state IN ('PENDING', 'ACCEPTED', 'REJECTED')),
  CONSTRAINT ck_admission_version CHECK (version >= 0),
  CONSTRAINT ck_admission_timestamps CHECK (updated_at_unix_ms >= created_at_unix_ms)
);

CREATE INDEX idx_admission_pending_recovery
  ON risk_service.admission_journal (state, updated_at_unix_ms);

CREATE TABLE risk_service.cdc_delivery_lag (
  metric_name VARCHAR(128) PRIMARY KEY,
  lag_events BIGINT NOT NULL DEFAULT 0,
  updated_at_unix_ms BIGINT NOT NULL,
  CONSTRAINT ck_cdc_delivery_lag_non_negative CHECK (lag_events >= 0 AND updated_at_unix_ms >= 0)
);

INSERT INTO risk_service.cdc_delivery_lag (metric_name, lag_events, updated_at_unix_ms)
VALUES ('orders.validated', 0, 0);
