CREATE TABLE risk_service.risk_submissions_v6 (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  idempotency_key VARCHAR(255) NOT NULL,
  request_id VARCHAR(255) NOT NULL,
  session_id VARCHAR(255) NOT NULL,
  trading_day DATE NOT NULL,
  order_id VARCHAR(255) NOT NULL,
  client_order_id VARCHAR(255) NOT NULL,
  original_client_order_id VARCHAR(255) NOT NULL,
  command_type VARCHAR(64) NOT NULL,
  accepted BOOLEAN NOT NULL,
  reason_code VARCHAR(255) NOT NULL,
  reason_text TEXT NOT NULL,
  created_at_unix_ms BIGINT NOT NULL,
  outbox_event_id VARCHAR(255) NOT NULL UNIQUE,
  CONSTRAINT risk_submissions_business_key_key
    UNIQUE (session_id, trading_day, command_type, client_order_id)
);

CREATE INDEX idx_risk_submissions_idempotency_key
  ON risk_service.risk_submissions_v6 (idempotency_key);

INSERT INTO risk_service.risk_submissions_v6 (
  idempotency_key,
  request_id,
  session_id,
  trading_day,
  order_id,
  client_order_id,
  original_client_order_id,
  command_type,
  accepted,
  reason_code,
  reason_text,
  created_at_unix_ms,
  outbox_event_id
)
SELECT
  idempotency_key,
  request_id,
  session_id,
  trading_day,
  order_id,
  client_order_id,
  original_client_order_id,
  command_type,
  accepted,
  reason_code,
  reason_text,
  created_at_unix_ms,
  outbox_event_id
FROM risk_service.risk_submissions;

DROP TABLE risk_service.risk_submissions;

ALTER TABLE risk_service.risk_submissions_v6 RENAME TO risk_submissions;