CREATE TABLE risk_service.risk_submissions_v8 (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id VARCHAR(255) NOT NULL,
  sender_comp_id VARCHAR(255) NOT NULL,
  target_comp_id VARCHAR(255) NOT NULL,
  trading_day DATE NOT NULL,
  order_id VARCHAR(255) NOT NULL,
  cl_ord_id VARCHAR(255) NOT NULL,
  orig_cl_ord_id VARCHAR(255) NOT NULL,
  command_type VARCHAR(64) NOT NULL,
  accepted BOOLEAN NOT NULL,
  reason_code VARCHAR(255) NOT NULL,
  reason_text TEXT NOT NULL,
  created_at_unix_ms BIGINT NOT NULL,
  outbox_event_id VARCHAR(255) NOT NULL UNIQUE
);

INSERT INTO risk_service.risk_submissions_v8 (
  request_id,
  sender_comp_id,
  target_comp_id,
  trading_day,
  order_id,
  cl_ord_id,
  orig_cl_ord_id,
  command_type,
  accepted,
  reason_code,
  reason_text,
  created_at_unix_ms,
  outbox_event_id
)
SELECT
  request_id,
  CASE
    WHEN POSITION(':' IN session_id) > 0 AND POSITION('->' IN session_id) > POSITION(':' IN session_id)
      THEN SUBSTRING(
        session_id
        FROM POSITION(':' IN session_id) + 1
        FOR POSITION('->' IN session_id) - POSITION(':' IN session_id) - 1)
    ELSE ''
  END,
  CASE
    WHEN POSITION('->' IN session_id) > 0
      THEN SUBSTRING(session_id FROM POSITION('->' IN session_id) + 2)
    ELSE ''
  END,
  trading_day,
  order_id,
  client_order_id,
  original_client_order_id,
  command_type,
  accepted,
  reason_code,
  reason_text,
  created_at_unix_ms,
  outbox_event_id
FROM risk_service.risk_submissions;

DROP TABLE risk_service.risk_submissions;

ALTER TABLE risk_service.risk_submissions_v8 RENAME TO risk_submissions;

ALTER TABLE risk_service.risk_submissions
  ADD CONSTRAINT risk_submissions_business_key_key
  UNIQUE (sender_comp_id, target_comp_id, trading_day, command_type, cl_ord_id);