CREATE TABLE risk_service.outbox_v9 (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id UUID NOT NULL UNIQUE,
  topic VARCHAR(255) NOT NULL,
  message_key VARCHAR(255) NOT NULL,
  kafka_partition_id INTEGER,
  payload BYTEA NOT NULL,
  payload_type VARCHAR(255) NOT NULL,
  headers_json TEXT NOT NULL,
  aggregate_type VARCHAR(255) NOT NULL,
  aggregate_id VARCHAR(255) NOT NULL,
  created_at_unix_ms BIGINT NOT NULL
);

INSERT INTO risk_service.outbox_v9 (
  event_id,
  topic,
  message_key,
  kafka_partition_id,
  payload,
  payload_type,
  headers_json,
  aggregate_type,
  aggregate_id,
  created_at_unix_ms
)
SELECT
  CAST(event_id AS UUID),
  topic,
  message_key,
  kafka_partition_id,
  payload,
  payload_type,
  headers_json,
  aggregate_type,
  aggregate_id,
  created_at_unix_ms
FROM risk_service.outbox
ORDER BY id;

DROP TABLE risk_service.outbox;

ALTER TABLE risk_service.outbox_v9 RENAME TO outbox;

CREATE INDEX IF NOT EXISTS idx_outbox_created_at
  ON risk_service.outbox (created_at_unix_ms, id);

CREATE TABLE risk_service.risk_submissions_v9 (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id VARCHAR(255) NOT NULL,
  sender_comp_id VARCHAR(255) NOT NULL,
  target_comp_id VARCHAR(255) NOT NULL,
  trading_day DATE NOT NULL,
  order_id VARCHAR(255) NOT NULL,
  cl_ord_id VARCHAR(255) NOT NULL,
  orig_cl_ord_id VARCHAR(255) NOT NULL,
  command_type VARCHAR(64) NOT NULL,
  accepted BOOLEAN NOT NULL,
  reason_code VARCHAR(255) NOT NULL,
  reason_text TEXT NOT NULL,
  created_at_unix_ms BIGINT NOT NULL,
  outbox_event_id UUID NOT NULL UNIQUE
);

INSERT INTO risk_service.risk_submissions_v9 (
  request_id,
  sender_comp_id,
  target_comp_id,
  trading_day,
  order_id,
  cl_ord_id,
  orig_cl_ord_id,
  command_type,
  accepted,
  reason_code,
  reason_text,
  created_at_unix_ms,
  outbox_event_id
)
SELECT
  request_id,
  sender_comp_id,
  target_comp_id,
  trading_day,
  order_id,
  cl_ord_id,
  orig_cl_ord_id,
  command_type,
  accepted,
  reason_code,
  reason_text,
  created_at_unix_ms,
  CAST(outbox_event_id AS UUID)
FROM risk_service.risk_submissions
ORDER BY id;

DROP TABLE risk_service.risk_submissions;

ALTER TABLE risk_service.risk_submissions_v9 RENAME TO risk_submissions;

ALTER TABLE risk_service.risk_submissions
  ADD CONSTRAINT risk_submissions_business_key_key
  UNIQUE (sender_comp_id, target_comp_id, trading_day, command_type, cl_ord_id);