#!/usr/bin/env bash
set -Eeuo pipefail
IFS=$'\n\t'

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd -- "$script_dir/.." && pwd)"
# shellcheck source=scripts/lib/local-common.sh
source "$script_dir/lib/local-common.sh"
# shellcheck source=scripts/lib/local-image-transport.sh
source "$script_dir/lib/local-image-transport.sh"

transport="${SIMPLEMATCH_LOCAL_IMAGE_TRANSPORT:-$SIMPLEMATCH_LOCAL_IMAGE_TRANSPORT_DEFAULT}"
image_lock="${SIMPLEMATCH_LOCAL_IMAGE_LOCK:-$repo_root/out/local-images.lock}"
namespace="${SIMPLEMATCH_LOCAL_NAMESPACE:-simplematch-local}"
output_file=""
render_profile=""
render_services=()
render_services_output=""
output_temp=""

usage() {
  cat <<'EOF_USAGE'
Usage:
  scripts/render-local-kubernetes-manifest.sh [options]

Options:
  --transport MODE    registry (default) or kind-load.
  --image-lock PATH   Lockfile generated by publish-local-images.sh.
  --namespace NAME    Namespace to render (default: simplematch-local).
  --output PATH       Atomically replace PATH with the rendered manifest.
  -h, --help          Show this help.

Rendering is transport-aware but has no external runtime side effects. Both
modes use a transient outer Kustomization for namespace selection. registry
accepts only repository-owned lock profiles: a complete local-overlay lock or
the existing Matching-only certification lock. Every selected image must render
as the immutable registry digest reference. A full registry render additionally
rejects any remaining :local image. kind-load preserves the repository local
image names for compatibility.
EOF_USAGE
}

while (($# > 0)); do
  case "$1" in
    --transport)
      transport="${2:?--transport requires a value}"
      shift 2
      ;;
    --image-lock)
      image_lock="${2:?--image-lock requires a value}"
      shift 2
      ;;
    --namespace)
      namespace="${2:?--namespace requires a value}"
      shift 2
      ;;
    --output)
      output_file="${2:?--output requires a value}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      usage >&2
      simplematch_die "unknown option: $1"
      ;;
  esac
done

simplematch_local_image_transport_validate "$transport" || exit 2
[[ ${#namespace} -le 63 && "$namespace" =~ ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$ ]] ||
  simplematch_die "invalid Kubernetes namespace: $namespace"
simplematch_require_command kubectl

if [[ "$transport" == registry ]]; then
  render_profile="$(simplematch_local_image_lock_render_profile "$image_lock")" ||
    simplematch_die "local image lock is not a supported rendering profile: $image_lock"
  render_services_output="$(simplematch_local_image_lock_render_services "$image_lock")" ||
    simplematch_die "unable to resolve rendering services from local image lock: $image_lock"
  mapfile -t render_services <<<"$render_services_output"
  ((${#render_services[@]} > 0)) || simplematch_die 'registry rendering selected no local images'
fi

# Kustomize rejects absolute resource paths even with LoadRestrictionsNone.
# Keep the transient wrapper under repository-generated state so the tracked
# local overlay can be referenced by a stable relative path.
mkdir -p "$repo_root/out"
wrapper_dir="$(mktemp -d "$repo_root/out/.simplematch-local-kustomize.XXXXXX")"
rendered_manifest="$wrapper_dir/rendered.yaml"

cleanup() {
  rm -rf -- "$wrapper_dir"
  if [[ -n "$output_temp" ]]; then
    rm -f -- "$output_temp"
  fi
}
trap cleanup EXIT

kustomization="$wrapper_dir/kustomization.yaml"
{
  printf '%s\n' 'apiVersion: kustomize.config.k8s.io/v1beta1'
  printf '%s\n' 'kind: Kustomization'
  printf 'namespace: %s\n' "$namespace"
  printf '%s\n' 'resources:'
  printf '%s\n' '  - ../../deploy/k8s/overlays/local'

  if [[ "$transport" == registry ]]; then
    printf '%s\n' 'images:'
    for service in "${render_services[@]}"; do
      entry="$(simplematch_local_image_lock_entry "$image_lock" "$service")" ||
        simplematch_die "unable to resolve image lock entry for service: $service"
      IFS='|' read -r entry_service source_image registry_tag digest_reference <<<"$entry"
      source_repository="${source_image%:*}"
      registry_repository="${digest_reference%@*}"
      digest="${digest_reference##*@}"
      printf '  - name: %s\n' "$source_repository"
      printf '    newName: %s\n' "$registry_repository"
      printf '    digest: %s\n' "$digest"
    done
  fi
} >"$kustomization"

kubectl kustomize "$wrapper_dir" --load-restrictor LoadRestrictionsNone >"$rendered_manifest"
[[ -s "$rendered_manifest" ]] || simplematch_die 'kubectl kustomize produced an empty manifest'

if [[ "$transport" == registry ]]; then
  for service in "${render_services[@]}"; do
    entry="$(simplematch_local_image_lock_entry "$image_lock" "$service")" ||
      simplematch_die "unable to validate rendered image for service: $service"
    IFS='|' read -r entry_service source_image registry_tag digest_reference <<<"$entry"
    source_repository="${source_image%:*}"

    grep -Fq "image: ${digest_reference}" "$rendered_manifest" ||
      simplematch_die "rendered manifest is missing digest-pinned image for service $service: $digest_reference"
    if grep -Fq "image: ${source_repository}:" "$rendered_manifest" ||
       grep -Fq "image: ${source_repository}@" "$rendered_manifest"; then
      simplematch_die "rendered manifest still contains mutable/local source repository for service $service: $source_repository"
    fi
  done

  if [[ "$render_profile" == full ]] && grep -Eq '^[[:space:]]*image:[[:space:]]+[^[:space:]]+:local[[:space:]]*$' "$rendered_manifest"; then
    simplematch_die 'full registry render still contains at least one mutable :local image'
  fi
fi

if [[ -n "$output_file" ]]; then
  mkdir -p "$(dirname -- "$output_file")"
  output_temp="$(mktemp "${output_file}.tmp.XXXXXX")"
  cp -- "$rendered_manifest" "$output_temp"
  mv -f -- "$output_temp" "$output_file"
  output_temp=""
  simplematch_info "Rendered local Kubernetes manifest: $output_file"
else
  cat "$rendered_manifest"
fi
