CREATE SCHEMA IF NOT EXISTS account_service;

CREATE TABLE account_service.account_limits
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id           VARCHAR(255)   NOT NULL,
    scope_type           VARCHAR(64)    NOT NULL,
    scope_key            VARCHAR(255)   NOT NULL,
    trading_day          DATE           NOT NULL,
    currency             VARCHAR(3)     NOT NULL,
    limit_total_notional NUMERIC(38, 8) NOT NULL,
    reserved_notional    NUMERIC(38, 8) NOT NULL DEFAULT 0,
    utilized_notional    NUMERIC(38, 8) NOT NULL DEFAULT 0,
    available_notional   NUMERIC(38, 8) NOT NULL,
    updated_at_unix_ms   BIGINT         NOT NULL,
    CONSTRAINT uq_account_limits_scope UNIQUE (account_id, scope_type, scope_key, trading_day),
    CONSTRAINT ck_account_limits_scope_type CHECK (LENGTH(TRIM(scope_type)) > 0),
    CONSTRAINT ck_account_limits_scope_key CHECK (LENGTH(TRIM(scope_key)) > 0),
    CONSTRAINT ck_account_limits_currency CHECK (currency = 'TWD'),
    CONSTRAINT ck_account_limits_notional_values CHECK (
        limit_total_notional >= 0
            AND reserved_notional >= 0
            AND utilized_notional >= 0
            AND available_notional >= 0
            AND available_notional = limit_total_notional - reserved_notional - utilized_notional),
    CONSTRAINT ck_account_limits_updated_at CHECK (updated_at_unix_ms >= 0)
);

CREATE TABLE account_service.account_positions
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id         VARCHAR(255)   NOT NULL,
    symbol             VARCHAR(64)    NOT NULL,
    long_qty           NUMERIC(38, 8) NOT NULL DEFAULT 0,
    short_qty          NUMERIC(38, 8) NOT NULL DEFAULT 0,
    updated_at_unix_ms BIGINT         NOT NULL,
    CONSTRAINT uq_account_positions_account_symbol UNIQUE (account_id, symbol),
    CONSTRAINT ck_account_positions_symbol CHECK (LENGTH(TRIM(symbol)) > 0),
    CONSTRAINT ck_account_positions_quantities CHECK (long_qty >= 0 AND short_qty >= 0),
    CONSTRAINT ck_account_positions_updated_at CHECK (updated_at_unix_ms >= 0)
);

CREATE TABLE account_service.account_reservations
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id      VARCHAR(255)   NOT NULL,
    request_id          VARCHAR(255)   NOT NULL,
    order_id            VARCHAR(255)   NOT NULL,
    account_id          VARCHAR(255)   NOT NULL,
    symbol              VARCHAR(64)    NOT NULL,
    side                VARCHAR(16)    NOT NULL,
    quantity            NUMERIC(38, 8) NOT NULL,
    limit_price         NUMERIC(38, 8),
    reserved_notional   NUMERIC(38, 8) NOT NULL DEFAULT 0,
    status              VARCHAR(64)    NOT NULL,
    reason_code         VARCHAR(255)   NOT NULL DEFAULT '',
    reason_text         TEXT           NOT NULL DEFAULT '',
    created_at_unix_ms  BIGINT         NOT NULL,
    updated_at_unix_ms  BIGINT         NOT NULL,
    released_at_unix_ms BIGINT,
    CONSTRAINT uq_account_reservations_reservation_id UNIQUE (reservation_id),
    CONSTRAINT uq_account_reservations_request_id UNIQUE (request_id),
    CONSTRAINT uq_account_reservations_order_id UNIQUE (order_id),
    CONSTRAINT ck_account_reservations_identity CHECK (
        LENGTH(TRIM(reservation_id)) > 0
            AND LENGTH(TRIM(request_id)) > 0
            AND LENGTH(TRIM(order_id)) > 0
            AND LENGTH(TRIM(account_id)) > 0
            AND LENGTH(TRIM(symbol)) > 0),
    CONSTRAINT ck_account_reservations_side CHECK (side IN ('SIDE_BUY', 'SIDE_SELL')),
    CONSTRAINT ck_account_reservations_quantity CHECK (quantity > 0),
    CONSTRAINT ck_account_reservations_limit_price CHECK (limit_price IS NULL OR limit_price >= 0),
    CONSTRAINT ck_account_reservations_reserved_notional CHECK (reserved_notional >= 0),
    CONSTRAINT ck_account_reservations_status CHECK (status IN (
                                                                'RESERVATION_STATUS_ACCEPTED',
                                                                'RESERVATION_STATUS_REJECTED',
                                                                'RESERVATION_STATUS_RELEASED',
                                                                'RESERVATION_STATUS_APPLIED')),
    CONSTRAINT ck_account_reservations_timestamps CHECK (
        created_at_unix_ms >= 0
            AND updated_at_unix_ms >= created_at_unix_ms
            AND (released_at_unix_ms IS NULL OR released_at_unix_ms >= created_at_unix_ms))
);
