CREATE SCHEMA IF NOT EXISTS account_service;

CREATE TABLE IF NOT EXISTS account_service.account_limits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id VARCHAR(255) NOT NULL,
  scope_type VARCHAR(64) NOT NULL,
  scope_key VARCHAR(255) NOT NULL,
  trading_day DATE NOT NULL,
  currency VARCHAR(16) NOT NULL,
  limit_total_notional NUMERIC(38, 8) NOT NULL,
  reserved_notional NUMERIC(38, 8) NOT NULL DEFAULT 0,
  utilized_notional NUMERIC(38, 8) NOT NULL DEFAULT 0,
  available_notional NUMERIC(38, 8) NOT NULL,
  updated_at_unix_ms BIGINT NOT NULL,
  CONSTRAINT uq_account_limits_scope UNIQUE (account_id, scope_type, scope_key, trading_day)
);

CREATE INDEX IF NOT EXISTS idx_account_limits_account_day
  ON account_service.account_limits (account_id, trading_day);

CREATE TABLE IF NOT EXISTS account_service.account_positions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id VARCHAR(255) NOT NULL,
  symbol VARCHAR(64) NOT NULL,
  long_qty NUMERIC(38, 8) NOT NULL DEFAULT 0,
  short_qty NUMERIC(38, 8) NOT NULL DEFAULT 0,
  updated_at_unix_ms BIGINT NOT NULL,
  CONSTRAINT uq_account_positions_account_symbol UNIQUE (account_id, symbol)
);

CREATE INDEX IF NOT EXISTS idx_account_positions_symbol
  ON account_service.account_positions (symbol);

CREATE TABLE IF NOT EXISTS account_service.account_reservations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reservation_id VARCHAR(255) NOT NULL,
  request_id VARCHAR(255) NOT NULL,
  order_id VARCHAR(255) NOT NULL,
  account_id VARCHAR(255) NOT NULL,
  symbol VARCHAR(64) NOT NULL,
  side VARCHAR(16) NOT NULL,
  quantity NUMERIC(38, 8) NOT NULL,
  limit_price NUMERIC(38, 8),
  reserved_notional NUMERIC(38, 8) NOT NULL DEFAULT 0,
  status VARCHAR(64) NOT NULL,
  reason_code VARCHAR(255) NOT NULL DEFAULT '',
  reason_text TEXT NOT NULL DEFAULT '',
  created_at_unix_ms BIGINT NOT NULL,
  updated_at_unix_ms BIGINT NOT NULL,
  released_at_unix_ms BIGINT,
  CONSTRAINT uq_account_reservations_reservation_id UNIQUE (reservation_id),
  CONSTRAINT uq_account_reservations_request_id UNIQUE (request_id),
  CONSTRAINT uq_account_reservations_order_id UNIQUE (order_id)
);

CREATE INDEX IF NOT EXISTS idx_account_reservations_account_status
  ON account_service.account_reservations (account_id, status);