ALTER TABLE account_service.account_limits
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE account_service.account_positions
    ADD COLUMN reserved_long_qty NUMERIC(38, 8) NOT NULL DEFAULT 0;

ALTER TABLE account_service.account_positions
    ADD COLUMN reserved_short_qty NUMERIC(38, 8) NOT NULL DEFAULT 0;

ALTER TABLE account_service.account_positions
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE account_service.account_reservations
    ADD COLUMN remaining_quantity NUMERIC(38, 8) NOT NULL DEFAULT 0;

ALTER TABLE account_service.account_reservations
    ADD COLUMN filled_quantity NUMERIC(38, 8) NOT NULL DEFAULT 0;

ALTER TABLE account_service.account_reservations
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

UPDATE account_service.account_reservations
SET remaining_quantity = quantity
WHERE remaining_quantity = 0;

ALTER TABLE account_service.account_positions
    ADD CONSTRAINT ck_account_positions_reserved_quantities
        CHECK (reserved_long_qty >= 0 AND reserved_short_qty >= 0
            AND reserved_long_qty <= long_qty
            AND reserved_short_qty <= short_qty);

ALTER TABLE account_service.account_reservations
    ADD CONSTRAINT ck_account_reservations_fill_quantities
        CHECK (filled_quantity >= 0 AND remaining_quantity >= 0
            AND (status = 'RESERVATION_STATUS_RELEASED'
                OR filled_quantity + remaining_quantity = quantity));

CREATE TABLE account_service.reservation_request_locks
(
    request_id         VARCHAR(255) PRIMARY KEY,
    created_at_unix_ms BIGINT NOT NULL,
    CONSTRAINT ck_reservation_request_locks_created_at CHECK (created_at_unix_ms >= 0)
);

CREATE TABLE account_service.outbox
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id           UUID         NOT NULL UNIQUE,
    topic              VARCHAR(255) NOT NULL,
    message_key        VARCHAR(255) NOT NULL,
    kafka_partition_id INTEGER,
    payload            BYTEA        NOT NULL,
    payload_type       VARCHAR(255) NOT NULL,
    headers_json       TEXT         NOT NULL,
    aggregate_type     VARCHAR(255) NOT NULL,
    aggregate_id       VARCHAR(255) NOT NULL,
    created_at_unix_ms BIGINT       NOT NULL,
    CONSTRAINT ck_account_outbox_required_text CHECK (
        LENGTH(TRIM(topic)) > 0
            AND LENGTH(TRIM(message_key)) > 0
            AND LENGTH(TRIM(payload_type)) > 0
            AND LENGTH(TRIM(headers_json)) > 0
            AND LENGTH(TRIM(aggregate_type)) > 0),
    CONSTRAINT ck_account_outbox_payload CHECK (OCTET_LENGTH(payload) > 0),
    CONSTRAINT ck_account_outbox_created_at CHECK (created_at_unix_ms >= 0)
);

CREATE INDEX idx_account_outbox_created_at
    ON account_service.outbox (created_at_unix_ms, id);

CREATE TABLE account_service.inbox
(
    consumer_name       VARCHAR(255) NOT NULL,
    event_id            UUID         NOT NULL,
    aggregate_id        VARCHAR(255) NOT NULL,
    aggregate_sequence  BIGINT,
    received_at_unix_ms BIGINT       NOT NULL,
    PRIMARY KEY (consumer_name, event_id),
    CONSTRAINT uq_account_inbox_aggregate_sequence
        UNIQUE (consumer_name, aggregate_id, aggregate_sequence),
    CONSTRAINT ck_account_inbox_received_at CHECK (received_at_unix_ms >= 0)
);
