apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: simplematch-local
resources:
  - ../../base
  - ../../postgresql.yaml
  - ../../redis.yaml
  - ../../kafka-kraft.yaml
  - ../../debezium-kafka-connect-local.yaml
configMapGenerator:
  - name: quickfix-gateway-fix-spec
    files:
      - FIX44.xml=../../../../config/quickfix/fix-spec/FIX44.xml
    options:
      disableNameSuffixHash: true
patches:
  - path: matching-scheduling-patch.yaml
  - path: local-runtime-patch.yaml
  - path: local-flyway-dependency-gates-patch.yaml
    target:
      group: batch
      version: v1
      kind: Job
      name: .*-flyway
images:
  - name: simplematch/account-service
    newTag: local
  - name: simplematch/risk-service
    newTag: local
  - name: simplematch/persistence
    newTag: local
  - name: simplematch/market-data-projection
    newTag: local
  - name: simplematch/marketdata-publisher
    newTag: local
  - name: simplematch/marketdata-streamer
    newTag: local
  - name: simplematch/query-service
    newTag: local
  - name: simplematch/flyway-runner
    newTag: local
  - name: simplematch-matching
    newTag: local
  - name: quickfix-gateway
    newTag: local
