apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: matching
spec:
  template:
    spec:
      nodeSelector: null
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution: null
      containers:
        - name: matching
          env:
            - name: MATCHING_MAX_RESTING_ORDERS_PER_INSTRUMENT
              value: "1024"
            - name: MATCHING_OUTPUT_CAPACITY
              value: "262144"
            - name: MATCHING_MAX_PENDING_PUBLICATIONS
              value: "250000"
          resources:
            requests:
              cpu: 100m
              memory: 2Gi
            limits:
              cpu: "1"
              memory: 2Gi
