CREATE SCHEMA IF NOT EXISTS market_data_projection;

CREATE TABLE market_data_projection.matching_event_inbox
(
    event_id              BYTEA PRIMARY KEY,
    payload_sha256        BYTEA        NOT NULL,
    partition_id          INTEGER      NOT NULL CHECK (partition_id BETWEEN 0 AND 14),
    offset_value          BIGINT       NOT NULL CHECK (offset_value >= 0),
    received_at_unix_ms   BIGINT       NOT NULL CHECK (received_at_unix_ms >= 0),
    CONSTRAINT matching_event_inbox_partition_offset_unique UNIQUE (partition_id, offset_value)
);

CREATE TABLE market_data_projection.partition_projection_progress
(
    partition_id           INTEGER      PRIMARY KEY CHECK (partition_id BETWEEN 0 AND 14),
    last_processed_offset  BIGINT       NOT NULL CHECK (last_processed_offset >= 0),
    recovery_state         VARCHAR(15) NOT NULL CHECK (recovery_state IN ('READY', 'RESYNC_REQUIRED')),
    updated_at_unix_ms     BIGINT       NOT NULL CHECK (updated_at_unix_ms >= 0)
);

CREATE TABLE market_data_projection.order_book_entries
(
    order_id                UUID        PRIMARY KEY,
    venue_mic               CHAR(4)     NOT NULL,
    symbol                  VARCHAR(4)  NOT NULL,
    side                    CHAR(1)     NOT NULL CHECK (side IN ('B', 'S')),
    price_units             BIGINT      NOT NULL CHECK (price_units > 0),
    leaves_quantity_shares  BIGINT      NOT NULL CHECK (leaves_quantity_shares > 0),
    last_event_id           BYTEA       NOT NULL,
    CONSTRAINT order_book_entries_instrument_symbol_nonempty CHECK (symbol <> '')
);

CREATE INDEX order_book_entries_top_five_idx
    ON market_data_projection.order_book_entries (venue_mic, symbol, side, price_units);

CREATE TABLE market_data_projection.instrument_market_data
(
    venue_mic                    CHAR(4)     NOT NULL,
    symbol                       VARCHAR(4)  NOT NULL,
    instrument_sequence          BIGINT      NOT NULL CHECK (instrument_sequence > 0),
    last_trade_price_units       BIGINT,
    last_trade_quantity_shares   BIGINT,
    snapshot_event_id            BYTEA,
    snapshot_payload             BYTEA,
    source_partition_id          INTEGER,
    source_offset_value          BIGINT,
    redis_snapshot_pending       BOOLEAN     NOT NULL,
    updated_at_unix_ms           BIGINT      NOT NULL CHECK (updated_at_unix_ms >= 0),
    PRIMARY KEY (venue_mic, symbol),
    CONSTRAINT instrument_market_data_symbol_nonempty CHECK (symbol <> ''),
    CONSTRAINT instrument_market_data_last_trade_consistent CHECK (
        (last_trade_price_units IS NULL AND last_trade_quantity_shares IS NULL)
            OR (last_trade_price_units > 0 AND last_trade_quantity_shares > 0)
    )
);

CREATE TABLE market_data_projection.market_data_events_outbox
(
    event_id                 BYTEA        PRIMARY KEY,
    source_matching_event_id BYTEA        NOT NULL,
    message_key              VARCHAR(9)  NOT NULL,
    topic                    VARCHAR(64) NOT NULL,
    payload                  BYTEA        NOT NULL,
    created_at_unix_ms       BIGINT       NOT NULL CHECK (created_at_unix_ms >= 0),
    published_at_unix_ms     BIGINT
);

CREATE INDEX market_data_events_outbox_pending_idx
    ON market_data_projection.market_data_events_outbox (published_at_unix_ms, created_at_unix_ms);

CREATE TABLE market_data_projection.matching_event_dead_letters
(
    dead_letter_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consumer_name            VARCHAR(48)  NOT NULL,
    event_id                 VARCHAR(64)  NOT NULL,
    topic                    VARCHAR(64)  NOT NULL,
    partition_id             INTEGER      NOT NULL CHECK (partition_id BETWEEN 0 AND 14),
    offset_value             BIGINT       NOT NULL CHECK (offset_value >= 0),
    payload                  BYTEA        NOT NULL,
    attempts                 INTEGER      NOT NULL CHECK (attempts > 0),
    failure_reason           VARCHAR(512) NOT NULL,
    dead_lettered_at_unix_ms BIGINT       NOT NULL CHECK (dead_lettered_at_unix_ms >= 0),
    CONSTRAINT matching_event_dead_letters_position_unique UNIQUE (consumer_name, topic, partition_id, offset_value)
);
